[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "cert.pem.tmpl"

# The location to place the rendered configuration file
dest = "/etc/postfix/cert.pem"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys = [ "/cert", "/ca", "/key" ]

# File ownership and mode information
owner = "root"
mode = "0644"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
reload_cmd = "/usr/sbin/postfix reload"
